on: [push, pull_request]
name: Test
jobs:
  Build-Windows:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Test
        run: go test ./... -v -race

  Build-Macos:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Test
        run: go test ./... -v -race

  Build-Linux:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Test
        run: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ./coverage.txt
          flag-name: Go-${{ matrix.go-version }}
          parallel: true
  Finish:
    needs: Build-Linux
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
